specific requirements
JosuehCA/OOP_Team2 pull request #21
Opened 2023-10-22 10:03 UTC by Deco1985

**Requirements definition and specification.**
The _"use case"_ format was used to specify requirements. Still need to review small details, I hope we have a meeting, thx guys.

2023-10-22 20:51 UTC, JosuehCA commented on Requerimientos.md
> +### **RF-05**: Etiquetado apartir de "Lotificación y Trazabilidad"
Modificar definición. Párrafo deshilvanado y un error ortográfico

2023-10-22 21:27 UTC, JosuehCA requested changes
Corrige todos los errores que se indican en los comentarios, y cambia el diseño del MD de la sección de requisitos. La información no se aprecia claramente.

2023-10-22 21:27 UTC, JosuehCA commented on Requerimientos.md
> +### **RNF-02**: Confiabilidad y precisión de la tegnología RFID
Faltas de ortografía

2023-10-22 21:27 UTC, JosuehCA commented on Requerimientos.md
> +      - La tegnología RFID deberá calibrarse adecuadamente para el registro de entrada y salida. De igual manera, la tegnología debe ser rápida y eficiente en cuanto al tiempo de respuesta, así como
Faltas de ortografía.

2023-10-22 21:27 UTC, JosuehCA commented on Requerimientos.md
> +      - El sistema se adaptará a las reglas de negocio del cliente y su empresa, en este caso, apegandonos al sistema de inventario "Lote"; asimismo, cumpliendo con las normas mexicanas e internacion
Faltas de ortografía y cohesión.

2023-10-22 21:27 UTC, JosuehCA commented on Requerimientos.md
> +### **RF-05**: Etiquetado apartir de "Lotificación y Trazabilidad"
Error ortográfico

2023-10-22 21:27 UTC, JosuehCA commented on Requerimientos.md
> +      - Los datos de nuestro programa se ordenarán a partir del sistema implementado por nuestro cliente, el sistema "Lote". La clasificación lote se rige por la trazabilidad, en resumen, es la infor
Modificar definición y cohesión de palabras

2023-10-22 21:27 UTC, JosuehCA commented on Requerimientos.md
> +| | Paso 3 - **Almacenamiento**: Los datos normalizados se almacenan en la base de datos. Cada registro se guarda en la base de datos de acuerdo con con su información detallada.|
Error de ortografía.

2023-10-22 21:27 UTC, JosuehCA commented on Requerimientos.md
> +| **Postcondición** | Si la base de datos es  funcional y accesible para consulta y análisis. Entonces se puede realizar el intercambio y almacenamiento de la información del inventario" |
Error de redacción. Coma en vez de punto, y seguir la idea desde ahí

2023-10-22 21:27 UTC, JosuehCA commented on Requerimientos.md
> +| **Precondición** | Tener calibrado la tegnología RFID |
Error ortográfico.

2023-10-22 21:27 UTC, JosuehCA commented on Requerimientos.md
> +| | Paso 1 - **Etiquetado de productos**: Se colocan las etiquetas RFID en cad lote que se digire a la congeladora. La etiqueta RFID se llena de la información trazabilizada por e usuario. |
Errores ortográficos.

2023-10-22 21:27 UTC, JosuehCA commented on Requerimientos.md
> +| | Paso 2 - **Registro de productos entrantes**: Al pasar por la puerta de la congeladora, el nuevo lote es escaneado automátocamente por el lector RFID. El lector envia al servidor la hora de entra
Error ortográfico.

2023-10-22 21:27 UTC, JosuehCA commented on Requerimientos.md
> +| | Paso 3 - **Registro de productos salientes**: Al pasar por la puerta de la congeladora, el lote almacenado es escaneado automátocamente por el lector RFID. El lector envia al servidor la hora de
Error ortográfico.

2023-10-22 21:27 UTC, JosuehCA commented on Requerimientos.md
> +| | Paso 3 - **Tags RFID defectuosos o ausentes**:  Puede haber casos en los que las etiquetas RFID estén dañadas, mal colocadas o ausentes en los productos, lo que impide la captura de datos.
Párrafo extra. Eliminar y actualizar conteo.

2023-10-22 21:27 UTC, JosuehCA commented on Requerimientos.md
> +| | Paso 3 - **Validación**: La plantilla resultante se se le entrega al usuario para su verificación correspondiente. |
Error ortográfico.

2023-10-22 21:27 UTC, JosuehCA commented on Requerimientos.md
> +| | Paso 4 - **Salvar y impresión**: El documento validado se guardará en el respaldo de la base de datos, para posteriormente el usuario pueda imprimir una copia en papel. |
Error ortográfico y de redacción.

2023-10-22 21:27 UTC, JosuehCA commented on Requerimientos.md
> +| | Paso 2 - **Fallos con la plantilla**: Puede haber un error de formato en el documento tal como un error de encuadre o los datos se colocaron en un lugar erroneo.
Error de acentuación.

2023-10-22 21:27 UTC, JosuehCA commented on Requerimientos.md
> +| | Paso 3 - **Fallos al momento de salvar**: Puede haber una interfecencia con el servidor al momento de guardar un documento de respaldo. En estos cosos no habria referencia de este documento digit
Error ortográfico y de acentuación.

2023-10-22 21:27 UTC, JosuehCA commented on Requerimientos.md
> +| **Requisito** | Definir los tiempos optimos para la generación de alertas. |
Error de acentuación.

2023-10-22 21:27 UTC, JosuehCA commented on Requerimientos.md
> +| **Precondición** | Tener en funcionamiento la base de datos, la tegnologia RFID y la lógica del programa. |
Error ortográfico.

2023-10-22 21:27 UTC, JosuehCA commented on Requerimientos.md
> +| | Paso 3 - **Selección de reporte o alerta**: La plantilla resultante se se le entrega al usuario para su verificación correspondiente. |
Error de redacción.

2023-10-22 21:27 UTC, JosuehCA commented on Requerimientos.md
> +| | Paso 4 - **Visualización de información**: El sistema muestra al usuario información detallada sobre el reporte y alerta seleccionada. Esto incluye datos como la fecha de ingleso del pescado a la
Error ortográfico y de acentuación.

2023-10-22 21:27 UTC, JosuehCA commented on Requerimientos.md
> +| **Postcondición** | Después de que se haya implementado la funcionalidad de "Reportes y alertas", el usuario podrá acceder al notificador de reportes y alertas, y estará informado sobre lso product
Errores ortográficos.

2023-10-22 21:27 UTC, JosuehCA commented on Requerimientos.md
> +| **Descripción general** | - Los datos de nuestro programa se ordenará a partir del sistema implementado por nuestro cliente, el sistema "Lote". La clasificación lote se rige por la trazabilidad, en
Errores de redacción y cohesión.

2023-10-22 21:27 UTC, JosuehCA commented on Requerimientos.md
> +| | Paso 1 - **Recolección de Datos de Trazabilidad**: La pescaderia recibe un nuevo lote de pescado en las instalaciones de procesamiento y a la congeladora. |
Error de acentuación.

2023-10-22 21:27 UTC, JosuehCA commented on Requerimientos.md
> +| | Paso 5 - **Almacenamiento  Seguimiento**: Se almacena fisicamente, se detecta por el lector RFID y se hace el seguimeinto en tiempo real de la fecha de cada Lote, hasta encontrar algún cambio.
Error ortográfico.

2023-10-22 21:27 UTC, JosuehCA commented on Requerimientos.md
> +| **Precondición** | Tener acceso al lector RFID o antena  al chip RFID |
Error de cohesión.

2023-10-22 21:27 UTC, JosuehCA commented on Requerimientos.md
> +| | Paso 2 - **Selección de componentes y etiquetas RFID adecuadas**: Se eliguen  componentes RFID que estén diseñados para funcionar en las condiciones ambientales identificadas en el paso 1. |
Error ortográfico.

2023-10-22 21:27 UTC, JosuehCA commented on Requerimientos.md
> +| | Paso 2 - **Altos niveles de humedad**: En condiciones de alta humedad o exposición a agua directa, como en entornos acuáticos o cuando el equipo RFID está constantemente mojado, es posible que el
Errores ortográficos.

2023-10-22 21:27 UTC, JosuehCA commented on Requerimientos.md
> +| **Postcondición** | Si la investigación es efectiva y se define el tipo de tegnologia RFID, se garantiza una implementación de la tegnologia. |
Error ortográfico.

2023-10-22 21:27 UTC, JosuehCA commented on Requerimientos.md
> +| **Postcondición** | Con la implementación exitosa de esta tegnología, se estará a uns pasos de concluir el POC.  |
Errores ortográficos.

2023-10-22 21:27 UTC, JosuehCA commented on Requerimientos.md
> +| | Paso 1 - **Diseño de la Interfaz**: Se realiarán dibujos, bocetos y pruebas de diseño para la IU. |
Error ortográfico.

2023-10-22 21:27 UTC, JosuehCA commented on Requerimientos.md
> +| | Paso 2 - **Desarrollo de la Interfaz**: Una vez que el diseño de la interfaz esté listo y aprobado, los proramadores entran a la fase de desarrollo. |
Error ortográfico.

2023-10-22 21:27 UTC, JosuehCA commented on Requerimientos.md
> +| | Paso 2 - **Errores en los datos de trazabilidad**: Se despliegará un mensaje de error que indique la pérdida de conexión y sugiera intentar nuevamente cuando se restablezca la conexión.
Error de redacción en "despliegará" -> "desplegará"

2023-10-22 21:27 UTC, JosuehCA commented on Requerimientos.md
> +| | Paso 4 - **Error del servidor o de la base de datos**: la interfaz debe mostrar un mensaje de error genérico e informar al usuario que se está trabajando en solucionar el problema.
No se comenzó con mayúscula.

2023-10-22 21:27 UTC, JosuehCA commented on Requerimientos.md
> +| **Requisito** | Implementar la tegnologia RFID |
Error ortográfico.

2023-10-22 21:27 UTC, JosuehCA commented on Requerimientos.md
> +| **Descripción** | - La tegnología RFID deberá calibrarse adecuadamente para el registro de entrada y salida. De igual manera, la tegnología debe ser rápida y eficiente en cuanto al tiempo de respue
Errores ortográficos y de redacción.

2023-10-22 21:27 UTC, JosuehCA commented on Requerimientos.md
> +| **Requisito** | Se deben cumplir ciertas caracteristicas tanto por parte de la Escalabilidad y de la Mantebilidad. |
Error de acentuación y redacción.

2023-10-22 21:27 UTC, JosuehCA commented on Requerimientos.md
> +| **Objetivo** | Garantizar que el POC cumpla con un 100% de precisión en el sistema Litificado de acuerdo a las reglas de negocio del cliente y las normas que la rigen.|
"Litificado"?

2023-10-22 21:27 UTC, JosuehCA commented on Requerimientos.md
> +| **Descripción** |- El sistema se adaptará a las reglas de negocio del cliente y su empresa, en este caso, apegandonos al sistema de inventario "Lote"; asimismo, cumpliendo con las normas mexicanas
Errores de acentuación y redacción.

2023-10-23 16:12 UTC, JosuehCA approved these changes
Bien. Mejora tu ortografía. Se modificó el impacto y la urgencia del RF-04

2023-10-25 14:37 UTC, RicardoCv0 approved these changes
Buen trabajo

2023-10-25 14:38 UTC, merged